version: '2.3'

services:
  db:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: 'passwordpusher_user'
      MYSQL_PASSWORD: 'passwordpusher_passwd'
      MYSQL_DATABASE: 'passwordpusher_db'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - /var/lib/pwpush-mysql/data:/var/lib/pwpush-mysql/data

  pwpush:
    image: docker.io/pglombardo/pwpush-mysql:release
    ports:
      - "5100:5100"
    depends_on:
      - db
    links:
     - db:mysql
